---

- hosts: ammad2@192.168.10.129
  become: true
  pre_tasks:

  - name: updating first
    apt:
      update_cache: yes
      upgrade: dist

- hosts: ammad2@192.168.10.129
  become: true
  tasks:

  - name: database server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

