---

- hosts: ammad2@192.168.10.129
  become: true
  pre_tasks:

  - name: updating first
    apt:
      update_cache: yes
      upgrade: dist

- hosts: ammad2@192.168.10.129
  become: true
  tasks:

  - name: installing and updating apache with php
    apt:
      update_cache: yes
      name:
        - apache2
        - libapache2-mo
