---


- hosts: all
  become: true
  tasks:

  - name: update apache2 package
    apt:
      update_cache: yes

  - name: install apache2 again
    apt:
      name: apache2
      state: latest

  - name: add php support
    apt:
      name: libapache2-mod-php
      state: latest
